---
language: ruby
sudo: false
cache: bundler
script: "bundle exec rake ci"
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    - rvm: jruby-9.1.2.0
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
  fast_finish: true
branches:
  only: master
notifications:
  email: false
